# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qmlmessages

# >> macros
# << macros

Summary:    Messaging application for nemo
Version:    0.1.4
Release:    1
Group:      Applications/System
License:    BSD
URL:        https://github.com/nemomobile/qmlmessages
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlmessages.yaml
Requires:   qt-components-qt5
Requires:   nemo-qml-plugin-messages-internal-qt5
Requires:   libcommhistory-qt5-declarative
Requires:   commhistory-daemon
Requires:   nemo-qml-plugin-contacts-qt5
Requires:   nemo-qml-plugin-dbus-qt5
Requires:   qmlcontacts
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Core) 
BuildRequires:  pkgconfig(Qt5Svg) 
BuildRequires:  pkgconfig(Qt5Contacts)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  pkgconfig(TelepathyQt5)
BuildRequires:  desktop-file-utils
Provides:   meego-handset-sms > 0.1.2
Provides:   meego-handset-sms-branding-upstream > 0.1.2
Provides:   peregrine-components-bridge-common = 1.1.7
Provides:   peregrine-components-layout = 1.1.7
Provides:   peregrine-libs = 1.1.7
Provides:   peregrine-qml-starter = 1.1.7
Provides:   peregrine-tablet-common = 1.1.7
Obsoletes:   meego-handset-sms <= 0.1.2
Obsoletes:   meego-handset-sms-branding-upstream <= 0.1.2
Obsoletes:   peregrine-components-bridge-common < 1.1.7
Obsoletes:   peregrine-components-layout < 1.1.7
Obsoletes:   peregrine-libs < 1.1.7
Obsoletes:   peregrine-qml-starter < 1.1.7
Obsoletes:   peregrine-tablet-common < 1.1.7

%description
Messaging application using Qt Quick for Nemo Mobile.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

qmake -qt=5 -recursive

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%post
# >> post
# << post

%files
%defattr(-,root,root,-)
%{_bindir}/qmlmessages
%{_datadir}/applications/qmlmessages.desktop
%{_datadir}/telepathy/clients/qmlmessages.client
%{_datadir}/dbus-1/services/org.freedesktop.Telepathy.Client.qmlmessages.service
%{_datadir}/dbus-1/services/org.nemomobile.qmlmessages.service
# >> files
# << files
